# Generated by Django 3.2.10 on 2021-12-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('otros_nombres', models.CharField(blank=True, max_length=50, null=True, verbose_name='Otros nombres')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('invertir_apellidos', models.BooleanField(blank=True, default=False, help_text='Esta opción permite poner el apellido materno antes del apellido paterno.', null=True, verbose_name='Invertir apellidos')),
                ('nombre_completo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre completo')),
                ('rut', models.CharField(blank=True, help_text='Rut con dígito verificador. Formato: 12345678-9', max_length=10, null=True, verbose_name='Rut')),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil')),
                ('fecha_nac', models.DateField(blank=True, help_text='Fecha de nacimiento.', null=True, verbose_name='Fecha de nacimiento')),
                ('fono_fijo', models.CharField(blank=True, help_text='Formato: 12 3456 7890', max_length=10, null=True, verbose_name='Teléfono Fijo')),
                ('fono_movil1', models.CharField(blank=True, help_text='Formato: 9 1234 5678', max_length=9, null=True, verbose_name='Teléfono Móvil 1')),
                ('fono_movil2', models.CharField(blank=True, help_text='Formato: 9 1234 5678', max_length=9, null=True, verbose_name='Teléfono Móvil 2')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('observaciones', models.TextField(blank=True, help_text='Escriba sus observaciones.', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de última modificación')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de desactivación')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['-id'],
            },
        ),
    ]
